let favPlaces = ["Madina Munawara", "Kashmir", "Skardu", "London", "Paris"];
console.log("Origional Order:", favPlaces);
console.log("Alphabetic Order:", [...favPlaces].sort());
console.log("Still Origional:",favPlaces);
console.log("Reverse Alphabetic Order:",[...favPlaces].sort().reverse());
console.log("Still Origional:", favPlaces);
console.log("Reverse Order:", favPlaces.reverse());
console.log("Back to Origional Order:", favPlaces.reverse());
console.log("Sort in Alphabetic Order:", favPlaces.sort());
console.log("Sort in Reverse Alphabetic Order:",favPlaces.sort().reverse());